# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [27]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001, size=(1000,20))

# print the shape of X
print('the shape of X is: ',X.shape)

the shape of X is:  (1000, 20)


In [28]:
X

array([[3104, 3423, 3208, ..., 1755, 4650, 4758],
       [1868, 2553, 2129, ...,  345, 1847,  785],
       [1817, 4109,  117, ..., 3847, 4405, 4319],
       ...,
       [1071, 3508, 2814, ..., 4171, 2118, 3445],
       [2474,  615, 1591, ...,  151, 1460, 2994],
       [2346, 4180, 1037, ..., 2579, 1576, 4442]])

Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [29]:
# Average of the values in each column of X
ave_cols = np.average(X,axis=0)

# Standard Deviation of the values in each column of X
std_cols = np.std(X,axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [30]:
# Print the shape of ave_cols
print('the shape of ave_cols is: ',ave_cols.shape)

# Print the shape of std_cols
print('the shape of std_cols is: ',std_cols.shape)

the shape of ave_cols is:  (20,)
the shape of std_cols is:  (20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [31]:
# Mean normalize X
X_norm = (X - ave_cols) / std_cols
X_norm

array([[ 0.43283192,  0.66267568,  0.48586608, ..., -0.50151392,
         1.44594713,  1.56114855],
       [-0.40458863,  0.06984256, -0.2687668 , ..., -1.49247314,
        -0.51634073, -1.19848554],
       [-0.43914239,  1.130128  , -1.67592285, ...,  0.96876033,
         1.27443071,  1.25622045],
       ...,
       [-0.94457582,  0.72059615,  0.21030968, ...,  1.19647011,
        -0.32662257,  0.64914262],
       [ 0.00599135, -1.25074433, -0.64503418, ..., -1.62881788,
        -0.78726667,  0.33587935],
       [-0.08073181,  1.17850863, -1.03249165, ...,  0.07759984,
        -0.7060589 ,  1.34165589]])

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [38]:
# Print the average of all the values of X_norm
print('the average of all the values of X_norm', np.mean(X_norm))

# Print the average of the minimum value in each column of X_norm
print('the average of the minimum value in each column of X_norm', np.mean(np.min(X_norm, axis=0)))

# Print the average of the maximum value in each column of X_norm
print('the average of he maximum value in each column of of X_norm', np.mean(np.max(X_norm, axis=0)))


the average of all the values of X_norm 1.9184653865522706e-17
the average of the minimum value in each column of X_norm -1.7213325466784817
the average of he maximum value in each column of of X_norm 1.7311267259297634


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [39]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([4, 0, 3, 2, 1])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [45]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])
print(row_indices)

[ 74 589 212 584 841  13 816 107 194 451 671 697 540 197 479 521 607  69
 665 716 165 839 705 452 137 629 113 154 494  41 108 583 525 802 945 948
  73 805 601 536 256 281 951 524 543 719  48 672 488 319 105 651 569 121
 435  11 906 287 699 279 244 919 294 808 777 439  36 711 761 751 631  83
  29 568 649 146 557 992 682 810 850 958 691 229 192 196 191 707 398 982
 895 764 275 484  84 614  32 692 195 643 151 428 252  50 729 278 440 571
 634 310 404 902 304 353   8 148 349 541 300 695 989 519 392 184 375 213
 625 903  64 874 616 561 851 305 814   4 743 155  38 918 202 845 842 597
 320 767  35   1 828 704 326 609 689 389 768 286 965  66 551 316  86 915
  80  24 801 360 573 264 710 775 449 619 140 327 262 706 885 995 878 980
 546 769 752 190 517 759 183 892 647 570 549 617 907 774 976 486 242 750
 924 447 206 867 608  68 804 390 309 872 787 391 833 818 513 167 156 469
 152 129 514 347 102 613  42 849 373 283 376 273  28 807 618 317 168 258
 875  57 622 534   2 930 602 559 412  71 179 166 24

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [50]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
training_idx, cross_val_idx, test_idx = row_indices[:600], row_indices[601:800], row_indices[801:]

# Create a Training Set
X_train = X_norm[training_idx,:]

# Create a Cross Validation Set
X_crossVal = X_norm[]

# Create a Test Set
X_test = X_norm[]

SyntaxError: invalid syntax (<ipython-input-50-c396e3cf93ca>, line 6)

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [ ]:
# Print the shape of X_train
print('the shape of X_train is: ',X_train.shape)

# Print the shape of X_crossVal
print('the shape of X_crossVal is: ',X_crossVal.shape)

# Print the shape of X_test
print('the shape of X_test is: ',X_test.shape)
