# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [1]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001, size=(1000,20))

# print the shape of X
print('the shape of X is: ',X.shape)

the shape of X is:  (1000, 20)


In [2]:
X

array([[1093, 3832, 1683, ..., 4345, 2235, 1980],
       [2492, 1211,  262, ..., 2531, 1385, 2821],
       [4544, 1332, 1728, ..., 3356, 3703, 3752],
       ...,
       [4531,  869, 2229, ...,  473, 2389, 1928],
       [ 797, 3320, 2754, ..., 3470, 3482, 1584],
       [2386, 4072, 4898, ..., 1657, 4999, 1485]])

Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [3]:
# Average of the values in each column of X
ave_cols = np.average(X,axis=0)

# Standard Deviation of the values in each column of X
std_cols = np.std(X,axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [4]:
# Print the shape of ave_cols
print('the shape of ave_cols is: ',ave_cols.shape)

# Print the shape of std_cols
print('the shape of std_cols is: ',std_cols.shape)

the shape of ave_cols is:  (20,)
the shape of std_cols is:  (20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [5]:
# Mean normalize X
X_norm = (X - ave_cols) / std_cols
X_norm

array([[-0.98165974,  0.86522068, -0.55046438, ...,  1.27430093,
        -0.20170274, -0.36511349],
       [ 0.00372177, -0.91759085, -1.54400667, ...,  0.01038515,
        -0.79833597,  0.20750301],
       [ 1.44904189, -0.83528632, -0.51900104, ...,  0.58520903,
         0.82871794,  0.84139833],
       ...,
       [ 1.43988538, -1.15022021, -0.16870921, ..., -1.42353914,
        -0.09360684, -0.40051903],
       [-1.19014646,  0.51695685,  0.19836306, ...,  0.66463924,
         0.6735933 , -0.63474028],
       [-0.07093902,  1.02846935,  1.69741631, ..., -0.59857978,
         1.73840813, -0.70214698]])

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [6]:
# Print the average of all the values of X_norm
print('the average of all the values of X_norm', np.mean(X_norm))

# Print the average of the minimum value in each column of X_norm
print('the average of the minimum value in each column of X_norm', np.mean(np.min(X_norm, axis=0)))

# Print the average of the maximum value in each column of X_norm
print('the average of he maximum value in each column of of X_norm', np.mean(np.max(X_norm, axis=0)))


the average of all the values of X_norm 1.9895196601282805e-17
the average of the minimum value in each column of X_norm -1.7268497776705982
the average of he maximum value in each column of of X_norm 1.7406197210771925


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [7]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([0, 2, 4, 1, 3])

# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [8]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])
print(row_indices)

[148 116 700 830 890 911 193  28 361 874 760 433 513  31 160 252 707 813
 462  16  68 977 774 431 748 437 974 721  98 543 988 351 291 660 500 604
   8 879  86 480 473 736 306 338 419 452  19  38 681 952 961 423  67 954
 757 162 799 376 319 235 680 554 541 869 289 142 281  65 740  39 329 624
 717 503 113 250 442 294 831 186 220  21 716 955 129 919 265 185 975  84
 396 348 139 323 925 504 343   4 810 388 126  17 313 432 407 144 770 673
  62  11   6 971 192 506 336  29 493 331 371  77 577 703 438 122  48 941
 309  80   5 408 517 734 206 899 951 173 239 775 187 674 849 141 538 368
 485 501 695 601 648 615 987 654 845 580 856 702 370 663 374 297 212 819
 470  87 698 269 652 288 514 488 668 558 337 650 102 640 581 487 411 814
 266 953 797 727 939 413 395 841 189 638 983  89 666  40 835 467  10 223
 400 836 166 902 280 256  90 778 409 498 471 918 231  64 287 209 846 789
 965  61 380 349 589 333 806  72 742 510 285 312 275 881 527 997 276 308
 593 933 300 658 163 450  32 476 320 229 645 923 52

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [9]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
training_idx, cross_val_idx, test_idx = row_indices[:600], row_indices[600:800], row_indices[800:]

# Create a Training Set
X_train = X_norm[training_idx,:]

# Create a Cross Validation Set
X_crossVal = X_norm[cross_val_idx,:]

# Create a Test Set
X_test = X_norm[test_idx,:]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [10]:
# Print the shape of X_train
print('the shape of X_train is: ',X_train.shape)

# Print the shape of X_crossVal
print('the shape of X_crossVal is: ',X_crossVal.shape)

# Print the shape of X_test
print('the shape of X_test is: ',X_test.shape)


the shape of X_train is:  (600, 20)
the shape of X_crossVal is:  (200, 20)
the shape of X_test is:  (200, 20)
