# Assessment

In [1]:
import numpy as np
import pandas as pd

How would you select the last 100 rows of a 2-dimensional NumPy array 'X'?

In [2]:
v = np.random.rand(250,2) * 10
v.shape

(250, 2)

In [3]:
v

array([[6.50415693e+00, 5.41007153e+00],
       [6.68953237e+00, 4.55243467e+00],
       [7.70997718e+00, 9.09273841e+00],
       [9.91656014e+00, 7.72204710e+00],
       [9.74030586e+00, 3.86762005e+00],
       [1.49097926e+00, 5.02750783e+00],
       [6.91174678e+00, 5.23001385e+00],
       [1.98084867e+00, 3.52735435e+00],
       [6.51197180e+00, 5.24712489e+00],
       [4.56510068e-01, 1.91546865e+00],
       [4.67317535e+00, 4.77830367e+00],
       [6.50885791e+00, 8.88875482e+00],
       [4.39793938e+00, 2.06286740e+00],
       [6.63355912e+00, 2.11247012e+00],
       [8.33433228e+00, 2.71839870e+00],
       [9.04118507e+00, 3.61366443e+00],
       [5.35799205e+00, 8.12625154e-01],
       [2.25912150e+00, 6.34329657e+00],
       [1.23376216e+00, 2.00154521e+00],
       [5.28774208e+00, 4.77311829e+00],
       [5.68847006e+00, 9.18707277e+00],
       [2.55220922e-01, 1.82765840e-01],
       [3.30554872e+00, 3.63126648e+00],
       [8.70841310e+00, 5.67724493e-01],
       [4.284512

In [4]:
v[-100:,]

array([[1.49052806e+00, 3.79103390e-01],
       [7.28488791e+00, 4.41913472e+00],
       [8.88682199e+00, 3.25103307e+00],
       [5.70373526e+00, 5.95135919e-01],
       [6.93467126e+00, 5.75152490e+00],
       [2.29548583e+00, 9.19430675e+00],
       [1.11049635e+00, 2.99565549e+00],
       [2.43774952e+00, 1.41094992e+00],
       [1.22881178e+00, 6.94141433e+00],
       [1.66186613e+00, 3.50164648e+00],
       [2.87860007e+00, 5.31291632e+00],
       [5.12251174e+00, 1.98688659e+00],
       [1.23418575e+00, 5.88447374e+00],
       [9.14923477e+00, 2.45925295e+00],
       [4.09094379e+00, 9.20344150e+00],
       [5.13149213e-01, 7.45350729e+00],
       [8.60431371e+00, 1.92839305e+00],
       [1.40001428e+00, 5.13211701e-01],
       [6.43149475e+00, 8.56444746e+00],
       [3.18591497e+00, 4.09049100e+00],
       [1.53894399e-01, 7.56820684e+00],
       [8.70884616e+00, 3.87047081e+00],
       [1.83276614e+00, 9.13446557e+00],
       [8.08235766e+00, 9.78790668e+00],
       [5.650452

Given a Pandas dataframe 'df' with columns 'gender' and 'age', how would you compute the average age for each gender?

In [5]:
NUM_PEOPLE = 100
gender = ['M','F']
people_gender =  np.array(np.random.choice(gender, NUM_PEOPLE))
people_age = np.array(np.random.choice(range(100), NUM_PEOPLE))

In [6]:
people_age

array([ 2, 14, 91, 71, 76, 99,  6, 56, 54, 81, 38, 29, 90, 60, 76, 94, 28,
       97, 12, 64, 72, 96, 89, 75, 29,  7, 75, 11, 69, 65, 70,  4, 79, 25,
       36, 45, 96, 19, 99, 81, 22, 41, 46, 26, 81, 12, 31, 63, 40, 49, 91,
        0, 74, 57, 94, 66, 56,  1, 68, 48, 66,  7, 89, 96, 31, 35, 79,  3,
       26, 21, 43, 31, 88, 83, 62, 77, 94, 55, 16, 26, 63, 79, 77, 21, 95,
       64, 64, 77, 78, 42, 96, 48, 83, 22, 96, 48, 51, 27, 19, 13])

In [7]:
df = pd.DataFrame({'gender': people_gender, 'age': people_age})

In [8]:
df.groupby('gender')['age'].mean()

gender
F    56.553191
M    52.433962
Name: age, dtype: float64

Which of the following commands would you use to visualize the distribution of 'height' values in a Pandas dataframe 'df'?

In [9]:
import matplotlib.pyplot as plt
df['age'].plot(kind='box')