## Working with built-in function

In this notebook, we're going to use some buil-in function provided by numpy for working with matrix

In [1]:
import numpy as np

Creating an ndarray with a specified shape that is full of zeros

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Creating an ndarray with a specified shape that is full of ones

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Both these methods take a `shape` as argument, where a `shape` is a `tuple` of `(rows, columns)`

Creating an ndarray with a specified shape that is full of any number we want

In [4]:
np.full((3,4), 3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

Creating an identity matrix

In [5]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
I.dtype

dtype('float64')

Creating a 4 x 4 diagonal matrix

In [7]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Creating ndarrays that have evenly spaced values within a given interval

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# create a vector in the given range 
np.arange(10,15) 

In [20]:
# create a vector of INTEGERS in the given range with a step of 4
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In the cases where non-integer elements are required, it is usually better to use the function `np.linespace()` instead of `np.arange()`

In [10]:
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

The `np.linspace(start, stop, N)` function returns `N` evenly spaced numbers over the closed interval \[start, stop\]. This means that both the start and thestop values are included

In [11]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

endpoint : bool, optional

If True, stop is the last sample. Otherwise, it is not included. Default is True.

In [12]:
np.linspace(1,20, 5, endpoint=False)

array([ 1. ,  4.8,  8.6, 12.4, 16.2])

`np.reshape(ndarray, new_shape)` function converts the given `ndarray` into the specified `new_shape`

In [13]:
print("from vector to matrix")
v = np.arange(10)
print(v)
print()
v = np.reshape(v, (2,5))
print(v)

from vector to matrix
[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]


in a more compact way

In [14]:
v = np.arange(10).reshape(2,5)
v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Random ndarrays are arrays that contain random numbers. Often in Machine Learning, you need to create random matrices, for example, when initializing the weights of a Neural Network. NumPy offers a variety of random functions to help us create random ndarrays of any shape.
The following line will produce a matrix 3x3 of random number with values in the interval [0,1]

In [15]:
X = np.random.random((3,3))
X

array([[0.14334464, 0.05156649, 0.19463827],
       [0.69685   , 0.29714785, 0.88401161],
       [0.53576789, 0.37277243, 0.93298419]])

To generate a matrix of integers in a given interval with a given size we can use

`np.random.randint(start,stop,size=(M,N))`

In [16]:
X = np.random.randint(1,30,size=(3,5))
X

array([[ 7, 19,  3, 26,  6],
       [ 4, 18, 14, 28, 27],
       [ 1, 26,  9, 15,  2]])

To generate ndarray of random floats drawn from normal (Gaussian) distribution

`np.random.normal(mean, standard deviation, size=shape)`

In [17]:
X = np.random.normal(0.5, 0.1, size=(1000,1000))
X

array([[0.46207184, 0.57620296, 0.34019726, ..., 0.41055036, 0.48923411,
        0.57909082],
       [0.4236585 , 0.40265034, 0.55147575, ..., 0.60773764, 0.51851461,
        0.48912055],
       [0.45980233, 0.28396299, 0.55198068, ..., 0.62962674, 0.47152806,
        0.54083428],
       ...,
       [0.46298673, 0.65794095, 0.65158119, ..., 0.35607675, 0.39762394,
        0.46978952],
       [0.4208099 , 0.60836002, 0.53347928, ..., 0.38053134, 0.47160124,
        0.5220238 ],
       [0.55334456, 0.49584668, 0.36937164, ..., 0.60639699, 0.66853079,
        0.3929403 ]])

In [18]:
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 0.5000844899300195
The maximum value in X is: 1.000826487328004
The minimum value in X is: 0.041484353022046117
X has 0 negative numbers
X has 1000000 positive numbers


## Test
Using the Built-in functions you learned about in the previous lesson, create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)

In [19]:
X = np.linspace(2,32,16).reshape(4,4)
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]
X has dimensions: (4, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 17.0
The maximum value in X is: 32.0
The minimum value in X is: 2.0
