In [1]:
import time
import numpy as np

## Performance

In [2]:
#create a random vector in numpy
x = np.random.random(10000000)

In [3]:
start = time.time()
sum(x)/len(x)
print(time.time()-start)

0.7080409526824951


In [4]:
start = time.time()
np.mean(x)
print(time.time()-start)

0.010666608810424805


numpy is optimized and fast on large arrays! 
This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.

## Creation 
At the core of NumPy is the ndarray, where nd stands for n-dimensional. An ndarray is a multidimensional array of elements all of the **same type**.

In [5]:
# defining a vector
x = np.array([1,2,3,5])

In [6]:
print(type(x))

<class 'numpy.ndarray'>


In [7]:
x.shape

(4,)

In [8]:
x.size

4

In [9]:
x.dtype

dtype('int64')

`shape` is used to get the current shape of a ndarray

`size` counts the total number of element in the ndarray.

The `.dtype` attribute tells us that the elements of `x` and `y` are stored in memory as signed 64-bit integers. Conversely, the `z` matrix is defined as a  Unicode strings of 21 characters.

Another great advantage of NumPy is that it can handle more data-types than Python lists.

In [10]:
# defining a matrix
y = np.array([[1,2,3,5],[6,7,8,9]])
print(y)

[[1 2 3 5]
 [6 7 8 9]]


In [11]:
y.shape

(2, 4)

In [12]:
y.size

8

In [13]:
print(y.dtype)

int64


In [14]:
# defining a mixed array
z = np.array([1,2,'numpy'])

In [15]:
type(z)

numpy.ndarray

In [16]:
z.dtype

dtype('<U21')

A numpy array can be saved in a file with the extention `.npy` as follows:

In [17]:
np.save('my_array_y', y)

The saved ndarray can then be loaded from disk as follows:

In [18]:
y = np.load('my_array_y.npy')

# We print y
print()
print(y)


[[1 2 3 5]
 [6 7 8 9]]


When loading an array from a file, make sure you include the name of the file together with the extension .npy, otherwise you will get an error.